### ISSUE TITLE
Restructure website so that current year is in root and not in folder

### ISSUE THREAD

**Issue by essenciary** [JuliaCon/juliacon.github.io#118]
If not too complicated as it would help for SEO.

**Comment by vchuravy** [comment]
The current way is setup so that URLs won't break later on.

**Comment by essenciary** [comment]
Got it. We could have the home page in the root -- it would get rid of the awkward JS redirect and the URL would be prettier and the content would be indexed more efficiently. For instance, it's not clear to me if the various home pages now don't compete for showing up in search results. How will google know what to pick for the home page? 

The rest of the content could stay under `2018`, say `/2018/talks`. Although the canonical structure should be `/talks/2018`. 

Anyway, I don't feel strongly about it as I don't think home page SEO is a big concern. But if a different home page will show up in the results, that'd be bad. Maybe we could add a link/notification on the old home pages to the current one...
