### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by essenciary** [JuliaCon/juliacon.github.io#125]
https://www.dropbox.com/sh/au67ga4rl9klv4p/AABAJWhTw9aEMkbuSyjla_sha?dl=0

**Comment by ChrisRackauckas** [comment]
That homepage is amazing! One comment is that I think having a little image on the top of each talk in the talk list is a little much. I am not sure so it needs for than the presenter's photo (or some project photo) associated with each card. But that design element is carried to other pages.

**Comment by essenciary** [comment]
Yes, we could try without them first and see what it looks like. Easier that way since they do require some work to prepare: from finding them, checking the licenses, resizing them for various resolutions, adding image attribution somewhere on the website, etc. 

Also, might be hard to find ones that are wide enough for the individual talk page, where the background fills up the whole width of the page.
