### ISSUE TITLE
JuliaCon 2018 AV Tracking issue

### ISSUE THREAD

**Issue by vchuravy** [JuliaCon/juliacon.github.io#153]
Please post them to https://goo.gl/forms/ng0ralIdLUuLTEyP2

**Comment by jarvist** [comment]
Atomistic simulation with Julia:
https://www.youtube.com/watch?v=Kbrj4EZbGWs
Is prepended by Carsten's QMC talk, before I start at ~18 minutes.

Conversely, Carsten's QMC talk is actually of a parallel session:
https://www.youtube.com/watch?v=pavEtxsaqlg

**Comment by ninjin** [comment]
Mike Innes is not me, yet he has my name in the ML workshop video. '^^

**Comment by JeffreySarnoff** [comment]
[Extended Precision](https://www.youtube.com/watch?v=adubwDKh5bs&t=218s&index=57&list=PLP8iPy9hna6Qsq5_-zrg0NTwqDSDYtfQB)
There was a connectivity problem which took the AV person a while to sort.
The recording should begin with the introduction, at elapsed time marker 3:48.

**Comment by EricForgy** [comment]
Looks like Jacob Quinn's HTTP.jl talk might have been cut short:

https://www.youtube.com/watch?v=oaB9WOYxOrk

**Comment by ViralBShah** [comment]
Would be nice to get the professional video of the 1.0 launch event.

**Comment by vchuravy** [comment]
Please use https://goo.gl/forms/ng0ralIdLUuLTEyP2 since it is easier to track issues. 
I have moved the issues reported here already to there
