### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by nassarhuda** [JuliaCon/juliacon.github.io#157]
My last name is Nassar (a instead of e)
https://github.com/JuliaCon/www.juliacon.org/blob/e3b930ac901385949dbb3a885c8ee8ae4f7534d2/2019/content19.html#L191

**Comment by ViralBShah** [comment]
Can you edit the website directly?

**Comment by nassarhuda** [comment]
Hmm... Weird, it looked like I didn't have the correct rights yesterday. But it worked now. 
Pull request: https://github.com/nassarhuda/www.juliacon.org/pull/1

**Comment by ViralBShah** [comment]
It seems the permissions are fixed. We do want the committee to be able to edit the website directly without PRs.
