### ISSUE TITLE
JuliaCon 2024: Supporting / Community Sponsors?

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/juliacon.github.io#470]
I think it would be very nice to have a section for companies, communities that:

- Support the conference with time (e.g. Volunteers from main committee but do not pay)
- Community Sponsors - groups that help our reach and diversity initiatives - will never pay money but are like extended marketing engine for us.

**Comment by bvdmitri** [comment]
Do we want a separate page for that?
