### ISSUE TITLE
copy of poster should be on the web page

### ISSUE THREAD

**Issue by alanedelman** [JuliaCon/juliacon.github.io#62]
even as a pdf

**Comment by StefanKarpinski** [comment]
With a copyright license that makes it usable as well. Otherwise anyone downloading it, printing it and putting it up places would be breaking the law. Presumably we own the copyright to this and MIT copy tech did the design as a work for hire?

**Comment by andreasnoack** [comment]
We'll pay for the design so I'd expect that it is ours, but I haven't received any information about this. I can ask, but do we really want to know?

**Comment by StefanKarpinski** [comment]
If the expectation is that it was done for hire, then we own the copyright as long as we pay them.

**Comment by alanedelman** [comment]
Just put it on line :-)

**Comment by StefanKarpinski** [comment]
We have the right to license this – all we need to do is pick a liberal CC license to allow others to use it too.

**Comment by jiahao** [comment]
[CC-BY-SA](http://creativecommons.org/licenses/by-sa/4.0/)?

**Comment by ninjin** [comment]
Or just simply [CC-BY](https://creativecommons.org/licenses/by/4.0/).  We should probably mention the poster in one of our announcements so that our legion of Julia users print it and put it up where is appropriate.

**Comment by alanedelman** [comment]
i'm betting any printout and use is covered by "fair use" at MIT
but it you like i"ll find out

I swear this has gone too far :-)

**Comment by StefanKarpinski** [comment]
CC-BY-SA seems fair. It doesn't seem reasonable for someone to use this poster to create something that no one else can use. Let's go with that and put it up.
