### ISSUE TITLE
Red and purple colors inverted in flag logo.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaCon/juliacon.github.io#92]
@ChrisRackauckas just noticed that the colors of the red and purple dots are inverted:

![image](https://cloud.githubusercontent.com/assets/4594825/18503235/633fbb50-7a21-11e6-88da-25e81d2d5933.png)

![image](https://cloud.githubusercontent.com/assets/4594825/18503246/7365b246-7a21-11e6-9220-29eeca815175.png)

**Comment by Ismael-VC** [comment]
I tried to fix it but it's no good :disappointed: 

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/4594825/18503889/efceea02-7a24-11e6-9f7b-188c127e84b0.gif)

**Comment by cormullion** [comment]
That's the back view! :)
